# Generated by Django 3.1.6 on 2022-01-31 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ExeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Name Length Should be greater than 3 characters.')])),
                ('position', models.CharField(choices=[('Developer', 'Developer'), ('Mentor', 'Mentor'), ('Alumni', 'Alumni'), ('Final year', 'Final year'), ('Pre-Final year', 'Pre-Final year'), ('Coordinator', 'Coordinator'), ('Executive', 'Executive'), ('Volunteer', 'Volunteer')], max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Full Stack', 'Full Stack'), ('Front End', 'Front End'), ('Back End', 'Back End'), ('Graphics Designer', 'Graphics Designer')], max_length=255, null=True)),
                ('image', models.URLField(max_length=255)),
                ('githubUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedInUrl', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100)),
                ('question_number', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
