# Generated by Django 3.1.6 on 2022-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gltf_model_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
