# Generated by Django 3.1.6 on 2022-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_question_gltf_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='exegallery',
            options={'verbose_name_plural': 'Exe Gallery'},
        ),
    ]
