# Generated by Django 3.1.6 on 2022-02-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20220131_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name_plural': 'LeaderBoard'},
        ),
        migrations.RemoveField(
            model_name='exemember',
            name='category',
        ),
    ]
